#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER hive WITH PASSWORD 'hive';
  CREATE DATABASE metastore;
  GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;

  \c metastore

  \i /hive/hive-schema-2.3.0.postgres.sql
  \i /hive/hive-txn-schema-2.3.0.postgres.sql

  \pset tuples_only
  \o /tmp/grant-privs
SELECT 'GRANT SELECT,INSERT,UPDATE,DELETE ON "' || schemaname || '"."' || tablename || '" TO hive ;'
FROM pg_tables
WHERE tableowner = CURRENT_USER and schemaname = 'public';
  \o
  \i /tmp/grant-privs
EOSQL

#keycloak

echo $POSTGRESQL_USER $POSTGRESQL_USER $POSTGRESQL_USER $POSTGRESQL_DATABASE

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
   -- CREATE ROLE $POSTGRESQL_USER superuser;
   CREATE USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASSWORD';
   ALTER ROLE $POSTGRESQL_USER superuser;
   ALTER USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASSWORD';
   CREATE DATABASE $POSTGRESQL_DATABASE;
   GRANT ALL PRIVILEGES ON DATABASE $POSTGRESQL_DATABASE TO $POSTGRESQL_USER;
   ALTER USER $POSTGRESQL_USER WITH SUPERUSER;
   ALTER ROLE $POSTGRESQL_USER WITH LOGIN;
EOSQL

echo $POSTGRESQL_USER $POSTGRESQL_USER $POSTGRESQL_USER $POSTGRESQL_DATABASE
